name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create release archive
      run: |
        # Create a clean release package
        mkdir -p release/mcp-jarvis
        
        # Copy essential files
        cp -r servers config scripts *.json *.md .env.example release/mcp-jarvis/
        
        # Create empty directories
        mkdir -p release/mcp-jarvis/data
        mkdir -p release/mcp-jarvis/logs
        
        # Create archives
        cd release
        tar -czf mcp-jarvis-${{ github.ref_name }}.tar.gz mcp-jarvis
        zip -r mcp-jarvis-${{ github.ref_name }}.zip mcp-jarvis
        cd ..
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          release/mcp-jarvis-${{ github.ref_name }}.tar.gz
          release/mcp-jarvis-${{ github.ref_name }}.zip
        generate_release_notes: true
        body: |
          ## 🚀 MCP Jarvis ${{ github.ref_name }}
          
          ### Installation
          1. Download and extract the archive
          2. Run `npm install`
          3. Run `node scripts/setup.js`
          4. Restart your AI assistant (Claude, VSCode, etc.)
          
          ### What's New
          See the auto-generated release notes below for changes.
          
          ### Compatibility
          - Claude Desktop ✅
          - VSCode + GitHub Copilot ✅
          - Visual Studio + Copilot ✅
          - Cursor IDE ✅
          - Any MCP-compatible tool ✅